spring:
  application:
    name: api

  config:
    import: "optional:configserver:"

  cloud:
    config:
      label: 0.0.1

custom:
  prop1: local-prop1
  prop2: local-prop2
  prop3: local-prop3
  #prop4: local-prop4
  #prop5: local-prop5
